# Note: audit statuses are only triggered in specific cases, so can't use here
status = ["ci (stable)", "ci (beta)", "clippy", "clippy_check"]
pr_status = ["ci (stable)", "ci (beta)", "clippy", "clippy_check"]
delete_merged_branches = true
use_codeowners = true
use_squash_merge = false
