name: Clippy check

on:
  push:
    branches-ignore:
      - '**.tmp'

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            # Note: some codegen tools actually format the code, so add rustfmt
            components: clippy, rustfmt
            override: true

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings
